### PR TITLE
Xml

### PR DESCRIPTION
**Pull request by Donaldblanc**
Added the ability to toggle between  XML and Json formats.

### CODE REVIEW

**Review by joepav — APPROVED** [review]
lgtm!

**Review by conor-jh — COMMENTED** [review]
At first glance, this looks good but I’m having trouble getting it to actually work.

### Steps to reproduce

1. Run `npm install`
2. Run `npm run build`
3. Run `npm run dev`
4. Submit `GET` request to http://svc.metrotransit.org/NexTrip/Providers?format=xml

At which point I get the following error:

```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at RequestBar.jsx:126
```

The request **does** come back with a `Content-Type: application/xml; charset=utf-8` header, so I’m not too sure what the issue is here—any ideas?

**Comment by RealJoelRivera** [comment]
Conor, I just ran your instructions above and I did not get any errors. The request worked fine.

**Comment by joepav** [comment]
Same here, no errors for me.

**Review by conor-jh — APPROVED** [review]
Alright, it’s working for me as well now 👌 Going to chalk it up to wonkiness from pulling the performance metrics changes and _then_ XML.

**Pull request merged**
